

after-login-command = []

after-startup-command = [
  # 'exec-and-forget borders active_color=0xfff2f2f2 inactive_color=0x3d3d3d width=6.0'
]

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 0

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focus-changed = ['move-mouse window-lazy-center']
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 14
    inner.vertical =  14
    outer.left =       12
    outer.bottom =     12
    outer.top =       12
    outer.right =      12

# Rules for specific windows
[[on-window-detected]]
  if.app-id = 'org.kicad.kicad' 
  if.window-title-regex-substring = 'KiCad \d+\.\d+' # Match titles ending like ' - KiCad 9.0'
  run = 'layout floating' 
[[on-window-detected]]
  if.app-id = 'org.kicad.kicad' 
  if.window-title-regex-substring = 'Assign Footprints' 
  run = 'layout floating' 

[[on-window-detected]]
  if.app-id = 'org.kicad.kicad' 
  if.window-title-regex-substring = 'Footprint Editor' 
  run = 'layout floating'

[[on-window-detected]]
  if.app-id = 'org.kicad.kicad' 
  if.window-title-regex-substring = 'Symbol Editor' 
  run = 'layout floating'   

[mode.main.binding]

    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    alt-f = 'fullscreen'

    alt-left = 'focus left'
    alt-down = 'focus down'
    alt-up = 'focus up'
    alt-right = 'focus right'

    alt-shift-left = 'move left'
    alt-shift-down = 'move down'
    alt-shift-up = 'move up'
    alt-shift-right = 'move right'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    cmd-left = 'workspace prev'
    cmd-right = 'workspace next'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
 
    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    alt-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    alt-left = ['join-with left', 'mode main']
    alt-down = ['join-with down', 'mode main']
    alt-up = ['join-with up', 'mode main']
    alt-right = ['join-with right', 'mode main']

    


