

after-login-command = []

after-startup-command = [
'exec-and-forget borders active_color=0xfff2f2f2 inactive_color=0x3d3d3d width=6.0'
]

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 0

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

# on-focus-changed = ['move-mouse window-lazy-center']
# on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 14
    inner.vertical =  14
    outer.left =       12
    outer.bottom =     12
    outer.top =       12
    outer.right =      12

# Rules for specific windows
[[on-window-detected]]
  if.app-id = 'org.kicad.kicad' 
  if.window-title-regex-substring = 'KiCad \d+\.\d+' # Match titles ending like ' - KiCad 9.0'
  run = 'layout floating' 
[[on-window-detected]]
  if.app-id = 'org.kicad.kicad' 
  if.window-title-regex-substring = 'Assign Footprints' 
  run = 'layout floating' 

[[on-window-detected]]
  if.app-id = 'org.kicad.kicad' 
  if.window-title-regex-substring = 'Footprint Editor' 
  run = 'layout floating'

[[on-window-detected]]
  if.app-id = 'org.kicad.kicad' 
  if.window-title-regex-substring = 'Symbol Editor' 
  run = 'layout floating'   

[mode.main.binding]


    ctrl-alt-cmd-slash = 'layout tiles horizontal vertical'
    ctrl-alt-cmd-comma = 'layout accordion horizontal vertical'

    ctrl-alt-cmd-f = 'fullscreen'

    ctrl-alt-cmd-left = 'focus left'
    ctrl-alt-cmd-down = 'focus down'
    ctrl-alt-cmd-up = 'focus up'
    ctrl-alt-cmd-right = 'focus right'

    ctrl-alt-cmd-shift-left = 'move left'
    ctrl-alt-cmd-shift-down = 'move down'
    ctrl-alt-cmd-shift-up = 'move up'
    ctrl-alt-cmd-shift-right = 'move right'

    ctrl-alt-cmd-minus = 'resize smart -50'
    ctrl-alt-cmd-equal = 'resize smart +50'

    cmd-left = 'workspace prev'
    cmd-right = 'workspace next'

    ctrl-alt-cmd-1 = 'workspace 1'
    ctrl-alt-cmd-2 = 'workspace 2'
    ctrl-alt-cmd-3 = 'workspace 3'
    ctrl-alt-cmd-4 = 'workspace 4'
    ctrl-alt-cmd-5 = 'workspace 5'
    ctrl-alt-cmd-6 = 'workspace 6'
    ctrl-alt-cmd-7 = 'workspace 7'
    ctrl-alt-cmd-8 = 'workspace 8'
    ctrl-alt-cmd-9 = 'workspace 9'

    ctrl-alt-cmd-shift-1 = 'move-node-to-workspace 1'
    ctrl-alt-cmd-shift-2 = 'move-node-to-workspace 2'
    ctrl-alt-cmd-shift-3 = 'move-node-to-workspace 3'
    ctrl-alt-cmd-shift-4 = 'move-node-to-workspace 4'
    ctrl-alt-cmd-shift-5 = 'move-node-to-workspace 5'
    ctrl-alt-cmd-shift-6 = 'move-node-to-workspace 6'
    ctrl-alt-cmd-shift-7 = 'move-node-to-workspace 7'
    ctrl-alt-cmd-shift-8 = 'move-node-to-workspace 8'
    ctrl-alt-cmd-shift-9 = 'move-node-to-workspace 9'
 
    ctrl-alt-cmd-tab = 'workspace-back-and-forth'
    ctrl-alt-cmd-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    ctrl-alt-cmd-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    # backspace = ['close-all-windows-but-current', 'mode main']

    ctrl-alt-cmd-left = ['join-with left', 'mode main']
    ctrl-alt-cmd-down = ['join-with down', 'mode main']
    ctrl-alt-cmd-up = ['join-with up', 'mode main']
    ctrl-alt-cmd-right = ['join-with right', 'mode main']
    

    


